# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/workspace/KXZ7C01/SoC_Embedded_Design_PL_UART/PS_Embedded_Design.srcs/system.xdc

# Block Designs: bd/ps_subsys/ps_subsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys || ORIG_REF_NAME==ps_subsys}]

# IP: bd/ps_subsys/ip/ps_subsys_processing_system7_0_0/ps_subsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_processing_system7_0_0 || ORIG_REF_NAME==ps_subsys_processing_system7_0_0}]

# IP: bd/ps_subsys/ip/ps_subsys_axi_iic_0_0/ps_subsys_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_axi_iic_0_0 || ORIG_REF_NAME==ps_subsys_axi_iic_0_0}]

# IP: bd/ps_subsys/ip/ps_subsys_proc_sys_reset_0_0/ps_subsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==ps_subsys_proc_sys_reset_0_0}]

# IP: bd/ps_subsys/ip/ps_subsys_axi_interconnect_1_0/ps_subsys_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_axi_interconnect_1_0 || ORIG_REF_NAME==ps_subsys_axi_interconnect_1_0}]

# IP: bd/ps_subsys/ip/ps_subsys_axi_uartlite_0_0/ps_subsys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_axi_uartlite_0_0 || ORIG_REF_NAME==ps_subsys_axi_uartlite_0_0}]

# IP: bd/ps_subsys/ip/ps_subsys_xbar_0/ps_subsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_xbar_0 || ORIG_REF_NAME==ps_subsys_xbar_0}]

# IP: bd/ps_subsys/ip/ps_subsys_auto_pc_0/ps_subsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_subsys_auto_pc_0 || ORIG_REF_NAME==ps_subsys_auto_pc_0}]

# XDC: bd/ps_subsys/ip/ps_subsys_processing_system7_0_0/ps_subsys_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_processing_system7_0_0 || ORIG_REF_NAME==ps_subsys_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_subsys/ip/ps_subsys_axi_iic_0_0/ps_subsys_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_axi_iic_0_0 || ORIG_REF_NAME==ps_subsys_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_subsys/ip/ps_subsys_axi_iic_0_0/ps_subsys_axi_iic_0_0_ooc.xdc

# XDC: bd/ps_subsys/ip/ps_subsys_proc_sys_reset_0_0/ps_subsys_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==ps_subsys_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_subsys/ip/ps_subsys_proc_sys_reset_0_0/ps_subsys_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_proc_sys_reset_0_0 || ORIG_REF_NAME==ps_subsys_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_subsys/ip/ps_subsys_proc_sys_reset_0_0/ps_subsys_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/ps_subsys/ip/ps_subsys_axi_uartlite_0_0/ps_subsys_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_axi_uartlite_0_0 || ORIG_REF_NAME==ps_subsys_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_subsys/ip/ps_subsys_axi_uartlite_0_0/ps_subsys_axi_uartlite_0_0_ooc.xdc

# XDC: bd/ps_subsys/ip/ps_subsys_axi_uartlite_0_0/ps_subsys_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_subsys_axi_uartlite_0_0 || ORIG_REF_NAME==ps_subsys_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_subsys/ip/ps_subsys_xbar_0/ps_subsys_xbar_0_ooc.xdc

# XDC: bd/ps_subsys/ip/ps_subsys_auto_pc_0/ps_subsys_auto_pc_0_ooc.xdc

# XDC: bd/ps_subsys/ps_subsys_ooc.xdc
