

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\riffa.obj \


_RES_FILE=$(OBJ_PATH)\$O\riffa.res
PRECOMPILED_INCLUDE_BASENAME=precomp.h




# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=r:\workspace\release\kxk7tc01\pcie_dma_128w125mhz_2.2.2\driver\windows\sys
OBJ_PATH=r:\workspace\release\kxk7tc01\pcie_dma_128w125mhz_2.2.2\driver\windows\sys
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
