# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/workspace/KXZ7C01/LED_Switch/vivado/LED_Switch.cache/wt [current_project]
set_property parent.project_path E:/workspace/KXZ7C01/LED_Switch/vivado/LED_Switch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/workspace/KXZ7C01/LED_Switch/vivado/LED_Switch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/workspace/KXZ7C01/LED_Switch/src/LED_Switch.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/workspace/KXZ7C01/LED_Switch/src/LED_Switch.xdc
set_property used_in_implementation false [get_files E:/workspace/KXZ7C01/LED_Switch/src/LED_Switch.xdc]


synth_design -top LED_Switch -part xc7z100ffg900-2


write_checkpoint -force -noxdef LED_Switch.dcp

catch { report_utilization -file LED_Switch_utilization_synth.rpt -pb LED_Switch_utilization_synth.pb }
