# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/imports/example_IBERT_SATA_10G.xdc

# IP: ip/IBERT_SATA_10G/IBERT_SATA_10G.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IBERT_SATA_10G || ORIG_REF_NAME==IBERT_SATA_10G}]
