# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/IBERT_SATA_10G_ex.cache/wt [current_project]
set_property parent.project_path E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/IBERT_SATA_10G_ex.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/IBERT_SATA_10G_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/imports/example_IBERT_SATA_10G.v
read_ip -quiet E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/IBERT_SATA_10G_ex.srcs/sources_1/ip/IBERT_SATA_10G/IBERT_SATA_10G.xci
set_property is_locked true [get_files E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/IBERT_SATA_10G_ex.srcs/sources_1/ip/IBERT_SATA_10G/IBERT_SATA_10G.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/imports/example_IBERT_SATA_10G.xdc
set_property used_in_implementation false [get_files E:/workspace/KXZ7C01/ProductCD/IBERT_SATA_10G/example/imports/example_IBERT_SATA_10G.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top example_IBERT_SATA_10G -part xc7z100ffg900-2


write_checkpoint -force -noxdef example_IBERT_SATA_10G.dcp

catch { report_utilization -file example_IBERT_SATA_10G_utilization_synth.rpt -pb example_IBERT_SATA_10G_utilization_synth.pb }
