# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/workspace/KXZ7C01/DDR3_Mem_900MHz/vivado_proj/ddr3_memtest.cache/wt [current_project]
set_property parent.project_path E:/workspace/KXZ7C01/DDR3_Mem_900MHz/vivado_proj/ddr3_memtest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/workspace/KXZ7C01/DDR3_Mem_900MHz/vivado_proj/ddr3_memtest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet E:/workspace/KXZ7C01/DDR3_Mem_900MHz/vivado_proj/ddr3_memtest.srcs/sources_1/ip/mig_7series_0/mig_7series_0.dcp
set_property used_in_implementation false [get_files E:/workspace/KXZ7C01/DDR3_Mem_900MHz/vivado_proj/ddr3_memtest.srcs/sources_1/ip/mig_7series_0/mig_7series_0.dcp]
read_vhdl -library xil_defaultlib E:/workspace/KXZ7C01/DDR3_Mem_900MHz/src/TestDDR.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/workspace/KXZ7C01/DDR3_Mem_900MHz/src/TestDDR.xdc
set_property used_in_implementation false [get_files E:/workspace/KXZ7C01/DDR3_Mem_900MHz/src/TestDDR.xdc]


synth_design -top TestDemo -part xc7z100ffg900-2


write_checkpoint -force -noxdef TestDemo.dcp

catch { report_utilization -file TestDemo_utilization_synth.rpt -pb TestDemo_utilization_synth.pb }
