# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.cache/wt [current_project]
set_property parent.project_path D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/functions.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/riffa.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/widths.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/trellis.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/types.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/ultrascale.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/xilinx.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tlp.vh
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/schedules.vh
}
read_verilog -library xil_defaultlib {
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/async_fifo.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/async_fifo_fwft.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/channel.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/channel_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/channel_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/channel_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/chnl_tester.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/counter.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/cross_domain_signal.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/demux.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/engine_layer.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/ff.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/fifo.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/fifo_packer_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/fifo_packer_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/fifo_packer_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/interrupt.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/interrupt_controller.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/mux.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/offset_flag_to_one_hot.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/offset_to_mask.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/one_hot_mux.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/pipeline.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/ram_1clk_1w_1r.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/ram_2clk_1w_1r.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/recv_credit_flow_ctrl.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/register.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/registers.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/reorder_queue.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/reorder_queue_input.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/reorder_queue_output.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/reset_controller.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/reset_extender.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/riffa.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_wrapper_KXZ7C100.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rotate.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_channel_gate.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_reader.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rx_port_requester_mux.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxc_engine_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxc_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxc_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxr_engine_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxr_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/rxr_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/scsdpram.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/sg_list_reader_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/sg_list_reader_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/sg_list_reader_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/sg_list_requester.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/shiftreg.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/sync_fifo.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/syncff.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/translation_xilinx.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_alignment_pipeline.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_data_fifo.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_data_pipeline.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_data_shift.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_engine.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_engine_selector.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_hdr_fifo.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_multiplexer.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_multiplexer_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_multiplexer_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_multiplexer_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_buffer_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_buffer_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_buffer_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_channel_gate_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_channel_gate_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_channel_gate_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_monitor_128.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_monitor_32.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_monitor_64.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/tx_port_writer.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/txc_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/txc_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/txr_engine_classic.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/riffa_hdl/txr_engine_ultrascale.v
  D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/KXZ7C100_Gen2x8If128.v
}
read_vhdl -library xil_defaultlib D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/MGT_DRP_Controller.vhd
read_ip -quiet D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.srcs/sources_1/ip/PCIeGen2x8If128/PCIeGen2x8If128.xci
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.srcs/sources_1/ip/PCIeGen2x8If128/source/PCIeGen2x8If128-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all d:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/proj/PCIE_DMA.srcs/sources_1/ip/PCIeGen2x8If128/synth/PCIeGen2x8If128_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/system.xdc
set_property used_in_implementation false [get_files D:/BaiduNetdiskDownload/crz01/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/CRZ01_DVD_V1.0/FPGA_RefDesign/15_PCIE_DMA_x8/PCIe_x8_DMA_128w250MHz_2.2.2/PCIe_x8_DMA_128w250MHz_2.2.2/src/system.xdc]


synth_design -top KXZ7C100_Gen2x8If128 -part xc7z100ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef KXZ7C100_Gen2x8If128.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file KXZ7C100_Gen2x8If128_utilization_synth.rpt -pb KXZ7C100_Gen2x8If128_utilization_synth.pb"
