set_property SRC_FILE_INFO {cfile:e:/workspace/KXZ7C01/SoC_Embedded_Design_PL_UART/PS_Embedded_Design.srcs/sources_1/bd/ps_subsys/ip/ps_subsys_processing_system7_0_0/ps_subsys_processing_system7_0_0.xdc rfile:../../../PS_Embedded_Design.srcs/sources_1/bd/ps_subsys/ip/ps_subsys_processing_system7_0_0/ps_subsys_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:ps_subsys_i/proc_arm/inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/workspace/KXZ7C01/SoC_Embedded_Design_PL_UART/PS_Embedded_Design.srcs/system.xdc rfile:../../../PS_Embedded_Design.srcs/system.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D19" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F19" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D18" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C19" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A18" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F20" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H18" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E20" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E18" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D20" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J18" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B20" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A20" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B21" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H17" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G21" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K18" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G22" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K17" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H21" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L18" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H22" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L17" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G20" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M17" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G19" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M19" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J21" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L20" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J19" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M20" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J20" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K20" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K21" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C22" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B22" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F22" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E21" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A23" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E22" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A24" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C21" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B24" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D24" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C24" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E23" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C23" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F23" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D23" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F24" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M21" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N21" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N23" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N24" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L23" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F25" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L28" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G29" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C29" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C26" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L29" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F29" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B29" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B26" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A27" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A29" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E27" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D26" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E26" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B25" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D25" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M30" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L30" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B27" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M29" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K30" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J28" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J30" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K27" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J29" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F30" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G30" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F28" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E30" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E25" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E28" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H28" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G27" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H27" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D29" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D28" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D30" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C28" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A28" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A30" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A25" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K28" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H29" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B30" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C27" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N22" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M22" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K25" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J25" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M24" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M25" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M26" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M27" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J23" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F27" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K22" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:648 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H26" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G24" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J26" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G25" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L27" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K26" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J24" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H23" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K23" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H24" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G26" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L25" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D21" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B19" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A22" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L13  IOSTANDARD LVCMOS18} [get_ports hdmi_out_clk]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  D15  IOSTANDARD LVCMOS18} [get_ports hdmi_vsync]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  B12  IOSTANDARD LVCMOS18} [get_ports hdmi_hsync]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  C12  IOSTANDARD LVCMOS18} [get_ports hdmi_data_e]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  C13  IOSTANDARD LVCMOS18} [get_ports hdmi_data[0]]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  C14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[1]]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  A12  IOSTANDARD LVCMOS18} [get_ports hdmi_data[2]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  A13  IOSTANDARD LVCMOS18} [get_ports hdmi_data[3]]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  A14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[4]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  B14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[5]]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H13  IOSTANDARD LVCMOS18} [get_ports hdmi_data[6]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J13  IOSTANDARD LVCMOS18} [get_ports hdmi_data[7]]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[8]]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[9]]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L14  IOSTANDARD LVCMOS18} [get_ports hdmi_data[10]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  L15  IOSTANDARD LVCMOS18} [get_ports hdmi_data[11]]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K13  IOSTANDARD LVCMOS18} [get_ports hdmi_data[12]]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  B11  IOSTANDARD LVCMOS18} [get_ports hdmi_data[13]]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  C11  IOSTANDARD LVCMOS18} [get_ports hdmi_data[14]]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E17  IOSTANDARD LVCMOS18} [get_ports hdmi_data[15]]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  D14  IOSTANDARD LVCMOS18} [get_ports spdif]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  B17   IOSTANDARD LVCMOS18} [get_ports i2s_mclk]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E15   IOSTANDARD LVCMOS18} [get_ports i2s_bclk]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E16   IOSTANDARD LVCMOS18} [get_ports i2s_lrclk]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  E13   IOSTANDARD LVCMOS18} [get_ports i2s_sdata_out]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  D13   IOSTANDARD LVCMOS18} [get_ports i2s_sdata_in]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U26  IOSTANDARD LVCMOS18 PULLTYPE PULLUP} [get_ports iic_scl]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U27  IOSTANDARD LVCMOS18 PULLTYPE PULLUP} [get_ports iic_sda]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB19   IOSTANDARD LVCMOS33} [get_ports pl_uart_rxd]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB20   IOSTANDARD LVCMOS33} [get_ports pl_uart_txd]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18} [get_ports {LED[0]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS18} [get_ports {LED[1]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS18} [get_ports {LED[2]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18} [get_ports {LED[3]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS15 PULLDOWN true} [get_ports {dip_switches[0]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K12 IOSTANDARD LVCMOS15 PULLDOWN true} [get_ports {dip_switches[1]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K10 IOSTANDARD LVCMOS15 PULLDOWN true} [get_ports {dip_switches[2]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS15 PULLDOWN true} [get_ports {dip_switches[3]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L10 IOSTANDARD LVCMOS15} [get_ports {push_buttons[0]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L9  IOSTANDARD LVCMOS15} [get_ports {push_buttons[1]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6  IOSTANDARD LVCMOS15} [get_ports {push_buttons[2]}]
